# Generated by Django 4.2 on 2023-05-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_occupant_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='concession',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='occupant',
            name='division',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='occupant',
            name='rangee',
            field=models.CharField(default='', max_length=50),
        ),
    ]
