# Generated by Django 4.2.1 on 2023-05-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_occupant_concession_occupant_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=50)),
                ('energie', models.CharField(max_length=50)),
                ('ges', models.CharField(default='', max_length=50)),
                ('surface', models.CharField(default='', max_length=50)),
                ('adresse', models.CharField(default='', max_length=50)),
                ('commune', models.CharField(default='', max_length=50)),
                ('code_postal', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Occupant',
        ),
    ]
