# Generated by Django 4.2.1 on 2023-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_habitation_delete_occupant'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitation',
            name='type_logement',
            field=models.CharField(default='', max_length=50),
        ),
    ]
