# Generated by Django 4.2.1 on 2023-05-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_habitation_type_logement'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitation',
            name='audit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
