# Generated by Django 4.2.1 on 2023-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_habitation_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitation',
            name='valeur',
            field=models.CharField(default='', max_length=50),
        ),
    ]
