# Generated by Django 4.2.1 on 2023-05-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_habitation_valeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitation',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='habitation',
            name='commune',
        ),
    ]
