# Generated by Django 4.2.1 on 2023-05-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_remove_habitation_code_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(default='', max_length=50)),
                ('fonciere', models.CharField(default='', max_length=50)),
                ('type_logement', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
