# Generated by Django 4.2.1 on 2023-05-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeur',
            name='date_transaction',
            field=models.CharField(default='', max_length=50),
        ),
    ]
