# Generated by Django 4.2.1 on 2023-05-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_valeur_date_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valeur',
            old_name='type_logement',
            new_name='code_postal',
        ),
        migrations.AddField(
            model_name='habitation',
            name='code_postal',
            field=models.CharField(default='', max_length=50),
        ),
    ]
