# Generated by Django 4.2.1 on 2023-05-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_rename_type_logement_valeur_code_postal_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='habitation',
            index=models.Index(fields=['adresse'], name='search_habi_adresse_392877_idx'),
        ),
        migrations.AddIndex(
            model_name='habitation',
            index=models.Index(fields=['annee'], name='search_habi_annee_338422_idx'),
        ),
        migrations.AddIndex(
            model_name='habitation',
            index=models.Index(fields=['energie'], name='search_habi_energie_206502_idx'),
        ),
        migrations.AddIndex(
            model_name='habitation',
            index=models.Index(fields=['audit'], name='search_habi_audit_5a29c0_idx'),
        ),
        migrations.AddIndex(
            model_name='habitation',
            index=models.Index(fields=['type_logement'], name='search_habi_type_lo_a624fe_idx'),
        ),
        migrations.AddIndex(
            model_name='valeur',
            index=models.Index(fields=['adresse'], name='search_vale_adresse_5c47cf_idx'),
        ),
        migrations.AddIndex(
            model_name='valeur',
            index=models.Index(fields=['code_postal'], name='search_vale_code_po_d455a0_idx'),
        ),
    ]
