# Generated by Django 4.2.1 on 2023-05-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_habitation_search_habi_adresse_392877_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='habitation',
            name='search_habi_adresse_392877_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitation',
            name='search_habi_annee_338422_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitation',
            name='search_habi_energie_206502_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitation',
            name='search_habi_audit_5a29c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitation',
            name='search_habi_type_lo_a624fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='valeur',
            name='search_vale_adresse_5c47cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='valeur',
            name='search_vale_code_po_d455a0_idx',
        ),
    ]
