# Generated by Django 4.2.1 on 2023-05-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_alter_habitation_adresse_alter_habitation_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitation',
            name='audit',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='habitation',
            index=models.Index(fields=['adresse', 'code_postal'], name='search_habi_adresse_66cbce_idx'),
        ),
        migrations.AddIndex(
            model_name='habitation',
            index=models.Index(fields=['adresse', 'energie', 'annee', 'audit', 'type_logement'], name='search_habi_adresse_5659c7_idx'),
        ),
    ]
