# Generated by Django 4.2.1 on 2023-05-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_alter_habitation_adresse_alter_habitation_annee_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='habitation',
            name='search_habi_adresse_66cbce_idx',
        ),
        migrations.RemoveIndex(
            model_name='habitation',
            name='search_habi_adresse_5659c7_idx',
        ),
        migrations.RemoveField(
            model_name='habitation',
            name='valeur',
        ),
        migrations.AlterField(
            model_name='habitation',
            name='adresse',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='habitation',
            name='annee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='habitation',
            name='audit',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='habitation',
            name='energie',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='habitation',
            name='type_logement',
            field=models.TextField(default='', max_length=50),
        ),
    ]
