# Generated by Django 4.2.1 on 2023-05-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_remove_habitation_search_habi_adresse_66cbce_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habitation',
        ),
    ]
